name: Git Deploy Action
description: Sync current repository to a remote repository on GitHub, GitLab, AWS CodeCommit, etc.
author: ayr-ton
branding:
  icon: upload-cloud
  color: blue
inputs:
  ssh_private_key:
    description: SSH private key for ssh connection to the target repository
    required: false
  target_repo_url:
    description: Target git repository URL
    required: true
  target_branch:
    description: Target git branch name, if any
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
